#!/bin/bash
BB=/home/bearbox/bearbox
PYPATH="$BB/core:$BB"

case "$1" in
    bear)   sudo env PYTHONPATH=$PYPATH python3 $BB/core/bear.py ;;
    nexus)  sudo env PYTHONPATH=$PYPATH python3 $BB/core/nexus.py ;;
    *)      echo "Usage: bbscreen [bear|nexus]" ;;
esac
